# mandatory - folder with images
source: '.source/first/source'

# optional - path and name of resulting file or 
# delete or leave empty ('') to save file near source folder with name output.psd
destination: 'path/to/folder/file.psd'

# mandatory - sample psd file with required parameters
template: 'C:/user/user/sample.psd'

# optional (default: false) - if true  - group images by dimensions
#                             if false - crop images to specified sample
precise: false
